# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://theimowski.com
gitlocation: https://github.com/theimowski/theimowski.github.io
gitbranch: master
title: Tomasz Heimowski Blog
subtitle: My thoughts on programming
description: >
    FsBlog aims to be a blog-aware static site generator, mostly built in F#. But don't worry,
    you won't even need to know any F# to get up and running. So long as you are comfortable
    using a command line or terminal, and have a degree of familiarity with Markdown and Razor
    syntax - you're good to go!

source: ../BlogContent/
blog: ../BlogContent/blog/
blogIndex: ../BlogContent/blog/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: ../Output/
deploy: deploy
themes: themes
